create database if not exists qfbap_dm;
use qfbap_dm;
CREATE TABLE `dm_user_basic` (
  `user_id` bigint,
  `user_name` string ,
  `user_gender` string ,
  `user_birthday` string ,
  `user_age` bigint ,
  `constellation` string ,
  `province` string ,
  `city` string ,
  `city_level` tinyint ,
  `e_mail` string   ,
  `op_mail` string  ,
  `mobile` bigint   ,
  `num_seg_mobile` int ,
  `op_mobile` string   ,
  `register_time` string  ,
  `login_ip` string   ,
  `login_source` string   ,
  `request_user` string   ,
  `total_score` decimal  ,
  `used_score` decimal  ,
  `is_blacklist` tinyint   ,
  `is_married` tinyint   ,
  `education` string ,
  `monthly_income` decimal  ,
  `profession` string ,
  `is_pregnant_woman` tinyint   ,
  `is_have_children` tinyint   ,
  `is_have_car` tinyint   ,
  `phone_brand` string ,
  `phone_brand_level` string   ,
  `phone_cnt` int ,
  `change_phone_cnt` int  ,
  `is_maja` tinyint   ,
  `majia_account_cnt` int  ,
  `loyal_model` string   ,
  `shopping_type_model` string  ,
  `weight` int  ,
  `height` int  ,
  `dw_date` string
) location '/qfbap/dm/dm_user_basic';
